name: kg-bio 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.7
  - jupyterlab=3
  - jupyter-offlinenotebook
  - pandas=1.3.5
  - requests
  - xlrd
  - openpyxl=2.6.0
  - lxml
  - matplotlib
  - matplotlib-venn
  - seaborn=0.11.0
  - biopython
  - papermill=2.1.0
  - ipywidgets=7.6.2
  - ipycytoscape>=1.0.3
  - plotly=5.5.0
  - py2neo 
  - monotonic
  - tabulate
  - pip
  - pip:
    - pybiopax==0.1.0
